### ISSUE TITLE
Figure/Table/Equation Numbering Issue

### ISSUE THREAD

**Issue by Abhi-1U** [Abhi-1U/texor#20]
### The Issue
This issue is an extension of issue #19 where the bookdown/distill supports the above features but are not provoked due to non-conformation of spec by R-markdown generated 

### Proposed Solution
Fix Issue #19 and see if it solves this as well.

### Metadata about software versions and System

Linux Mint 20.3 X86_64
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
RStudio 2022.02.3+492 "Prairie Trillium" 
pandoc 2.18
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)

**Comment by Abhi-1U** [comment]
For Images I am working on a lua filter for wrapping small R-markdown style codeblock around include graphics in images. 

```markdwon
```{r fig-ref, echo=FALSE, fig.cap='caption', fig.subcap=c('subcaption1, 'subcaption2'), fig.ncol = 2, fig.align='center', out.width='.49\\linewidth'}
knitr::include_graphics(c('image1.png','image2.png'))
```
```

**Comment by Abhi-1U** [comment]
- [ ] Figure 
- [ ] table
- [ ] equation

**Comment by Abhi-1U** [comment]
From what I have observed equations are not really numbered in R-markdown based samples,
so should we number the equations or not.

**Comment by cderv** [comment]
Equation can be numbered with R Markdown **bookdown** https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations if you need that

**Comment by Abhi-1U** [comment]
> Equation can be numbered with R Markdown **bookdown** https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations if you need that

Yes, I can consider implementing this, will discuss it further in the weekly meeting

**Comment by cderv** [comment]
I can't be here tomorrow but if you need equation numbering in HTML that would be how **bookdown** supports it.

**Comment by Abhi-1U** [comment]
Equation Numbering now enabled through modifications in the equation by this [Lua filter](https://github.com/Abhi-1U/tex-lua-filters/blob/ab12c7203178d7ca4e59348db8883f8fbb4b7dd8/bookdown_style_equation/bookdown-style-equations.lua)
