### ISSUE TITLE
Remove new paragraphs in abstract

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#28]
If the abstract has paragraphs, the current version will add new paragraph symbols (`¶`).

It would be good to avoid this - I guess when you extract the abstract you can replace `\n\n` with ` ` or something like that.

**Comment by Abhi-1U** [comment]
I have solved it using gsub in texor/article-tools.R/generate_rmd() function

````
abstract <- gsub("¶"," ", metadata$author[2])
metadata$abstract <- abstract
````
