### ISSUE TITLE
Fix alignment in equations

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#29]
Pandoc converts `\eqnarray` and `\align` environments to `\align`. For better alignment I think you can replace `& = &` or `=&` with `&=`. Note whitespace is optional, so something like

    gsub("& ?= ?&?", "& =", x)

**Comment by mitchelloharawild** [comment]
It could be simpler to persuade pandoc with a lua filter to give `\eqnarray` instead of `\align`.

**Comment by Abhi-1U** [comment]
This [function](https://github.com/Abhi-1U/texor/blob/229037e8cb69b19b914d7ae792e2b12c6c486549/R/filter-tools.R#L68-L96) tries to preserve the eqnarray format by adding $$ before and after the environment using gsub.
