### ISSUE TITLE
Use unicode characters to avoid unconverted LaTeX

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#30]
You can use unicode character directly in the markdown to avoid LaTeX commands that are not recognised. E.g.

\textasciitilde -> ~
\leq -> ≤

It appears to be safe to do a global replace, e.g. ≤ works fine in text or math mode.

**Comment by hturner** [comment]
You do not need to use the `\unicode` command. Rather I mean to copy the character (e.g. from https://www.compart.com/en/unicode/U+2264) and substitute it directly. I'm not sure where you are doing the substitution, but if we were doing it in R with `gsub()`, then:

    gsub("\\leq", "≤", x)
    
I've manually added `≤` both to text and to math in an example article and it showed up fine in the HTML. So this should work for other special characters.

`\sim` is different from `\textasciitilde`, so presumably the authors preferred the smaller tilde if they used the latter.

**Comment by Abhi-1U** [comment]
> I've manually added `≤` both to text and to math in an example article and it showed up fine in the HTML. So this should work for other special characters.
 
I cant seem to reproduce this, seems like something changes when the file is transformed from markdown to R-markdown and ≤ changes to â‰¤ and later mathjax is unable to show tilde in HTML in my case.
 

> You do not need to use the \unicode command. Rather I mean to copy the character (e.g. from https://www.compart.com/en/unicode/U+2264) and substitute it directly. I'm not sure where you are doing the substitution, but if we were doing it in R with gsub(), then:

I was replacing the Unicode values such as \U2264 for ≤

**Comment by hturner** [comment]
From the RStudio community link you sent, it seems it could be related to UTF-8 support on Windows. UTF-8 has been supported since R 4.2 (https://stat.ethz.ch/pipermail/r-announce/2022/000683.html) and this is what I am using for my tests (4.2.0 on Windows 10). Maybe you need to update R? For me it works in markdown or R markdown, e.g. in 2010-1/2009-23 this works:

   `induced ≤ 1`, and `spontaneous ≤ 1`. They are provided by

Looking closer at the case of \textasciitilde in 2010-1/2009-23, it is not converted because the authors put it in math mode, as, in `$\textasciitilde$`, which is not correct since this command is intended for text mode. If they had written `\textasciitilde` then this would have been converted to `\~` in the markdown and `~` in the HTML. Probably they were trying to preserve the space after the tilde, which should be done with `\textasciitilde{}`, or `\textasciitilde~`. So in that case you can just replace `$\textasciitilde$` with `\textasciitilde{}`.

**Comment by Abhi-1U** [comment]
I was using R version 4.0.0, hence that could be a reason, I will try upgrading the softwares. Thanks for the suggestion.
