### ISSUE TITLE
A few LaTeX math commands do not play well with MathJaX

### ISSUE THREAD

**Issue by Abhi-1U** [Abhi-1U/texor#4]
### The Issue
While the most majority of math commands are reliably converted, certain outlier function still exist, need to find a way to transform or make it viewable, also equation numbering seems to be having trouble too.

### Metadata about software versions and System

Linux Mint 20.3 X86_64
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
RStudio 2022.02.1 Build 461
pandoc 2.15
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian)

**Comment by Abhi-1U** [comment]
Commands not supported by MathJax wont be displayed properly, need to manually intervene and modify the equations.
unless alternative is found.

**Comment by cderv** [comment]
Just in case, I know some LaTeX command are available to MathJax only if some package extension has been loaded
http://docs.mathjax.org/en/v2.7-latest/tex.html#supported-latex-commands

But it is probably that not all math from LaTeX can be transformed to Mathjax. 

In this case, you can render the Math to an image using texPreview package probably: https://yonicd.github.io/texPreview/index.html

Could be better than using the LaTeX Math in the HTML document
