### ISSUE TITLE
\strong in table leads to missing data

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#62]
Another issue in Table 2 of RJ-2012-006, is that the most important data are highlighted with `\strong{}` but these values are missing in the HTML output (the values corresponding to Class 4).

**Comment by Abhi-1U** [comment]
I found this last week and fixed it since in commit https://github.com/Abhi-1U/texor/commit/ccafcfc0e83181bd98a9a8a1a2ea58c472c94202. Since those articles which were converted before this commit, it might have missing text. I will try to salvage some of those articles (if feasible).
