### ISSUE TITLE
Compare R-Journal to HTML with Python docs

### ISSUE THREAD

**Issue by jfine2358** [Abhi-1U/texor#65]
I'm a long standing Python user and developer, and similarly TeX. I believe a comparison with Python would help the readers of this article, and am willing to share what I can to help bring this about. In particular, the docs for Python 2.5 were authored in LaTeX. For Python 2.6 they were authored in ReStructured Text. 

The changeover took place in 2008. The difference in the resulting HTML is clear:
https://docs.python.org/release/2.6/
https://docs.python.org/release/2.5.4/

See also this master list of all versions of the documentation (from 1.4 onwards): https://www.python.org/doc/versions/

Perhaps a *dictionary of equivalents* would be a good idea.  To make a start, some of the equivalences (with links for Python) are:

* R-markdown | Restructured TexT |https://devguide.python.org/documentation/markup/
* R-markdown to HTML | Sphinx | https://www.sphinx-doc.org/en/master/
* ??? | Python Docstrings | https://peps.python.org/pep-0287/ 

More will follow soon. Please use the issue to ask questions about Python documentation.

**Comment by Abhi-1U** [comment]
Hi @jfine2358,
Thank you for your feedback; I appreciate the comparison with Python documentation. 
 However, I believe the goal of this package is slightly different. We're mostly concerned in converting legacy (LaTeX) R journal articles to R markdown and/or HTML. In that sense, comparing Python documentation to R documentation is beyond the scope of this package or paper. 
 The R community has been building modern web-based documentation for R, and we have the [roxygen2](https://cran.r-project.org/package=roxygen2) package to give capabilities similar to Python docstrings.
