### ISSUE TITLE
Make an optional param for autonumbering equations without `\nonumber`

### ISSUE THREAD

**Issue by Abhi-1U** [Abhi-1U/texor#68]
This will make it easier to choose what kind of numbering one wants to follow:

Notes: 
1. Equations existing with `\label{..}` or `(\#eq:xxx)` will be kept as is and will also be included in the numbering.
2. Equations with `\nonumber` will be skipped from the numbering.
3. Equations without `\nonumber` but if are a part of `\begin{equation*}` or some other non-numbered equations will be numbered. To prevent numbering this (add `\nonumber` or do not use the autonumbering option)
4. Equations without labels and `\nonumber` will be assigned a bookdown style label to facilitate numbering. This numbering will be try to mimic the auto numbering done in LaTeX.
5. Any `\tag{..}` with some custom numbering will not be supported, and will need to be removed from the equation in the article.
6. Equations with a `\label{...}` but are to be skipped from numbering will not be possible as to refer to equation bookdown will still add numbering.

**Comment by fzyxh** [comment]
You can test new feature with this [Sweave file](https://github.com/fzyxh/texor-playground/blob/main/equation_number/Comparisons.Rnw).
