### ISSUE TITLE
rnw_to_rmd: centre figures

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#80]
Currently `\centering` in a figure environment is ignored. 

I think figures should always be centred.

**Comment by Abhi-1U** [comment]
I think one possible way to fix numbering is by replacing figure objects with Rmarkdown code chunks to do the same.
[Here](https://abhi-1u.github.io/fig-code-chunk/) is a test sample for a potential [lua filter](https://github.com/Abhi-1U/fig-code-chunk) to do the same.
