### ISSUE TITLE
rnw_to_rmd: suppress package startup messages

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#81]
I believe that Sweave does not show messages and warnings in the code output, but these will appear in the R markdown output.

A particular case is the messages that appear when a package is loaded, which we rarely want to see in the output.

I think we can set the following in the settings chunk, to always suppress package startup messages:

```r
library <- function(...) suppressPackageStartupMessages(base::library(...))
```

**Comment by fzyxh** [comment]
In fact, R codes perform the same in both document expect some commands related to rendering LaTeX itself. And this is controlled by knitr when kniting R Markdown file.

For example, in `system.file("examples", "sweave_article", package = "texor")`, I used a setup code chunk to disable warning messages:

```r
<<setup,include=FALSE>>=
knitr::opts_chunk$set(warning = FALSE)
@
```

If I delete this code chunk, it may throw warnings in both output ( pdf from Sweave and HTML from R Markdown).

![image](https://github.com/user-attachments/assets/8f27de62-54c7-4a2a-b5bc-4f8adce34b60)
![image](https://github.com/user-attachments/assets/35eeb5bd-dcf9-46f1-8624-9c865242dd40)
