### ISSUE TITLE
rnw_to_rmd: improve default sectioning

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#83]
Currently `rnw_to_rmd()` uses numbered sections by default, similar to LaTeX. As we are using the `bookdown::html_document2` format, [this requires using H1 headers for sections](https://bookdown.org/yihui/rmarkdown/html-document.html#section-numbering).

This leads to poor formatting (section headers are as large as the title) and is [bad practice from an accessibility point of view](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/?utm_source=labnotes.org#best-practices-summarized). It also means that equations are numbered by section, which differs from the LaTeX default. 

`BiocStyle::html_document` adds code to [override the bookdown behaviour](https://code.bioconductor.org/browse/BiocStyle/blob/RELEASE_3_19/R/html_document.R#L104), resulting in the default LaTeX behaviour. However this would not be a good default for CRAN packages as it is a heavier dependency and you need to add conditional formats to ensure the vignette builds on CRAN (as I did for my [PlackettLuce package](https://github.com/hturner/PlackettLuce/blob/main/vignettes/Overview.Rmd#L40-L45)).

So as a default, I would suggest to use unnumbered sections and to use H2 for sections, H3 for subsections etc.

It would also be good to explore what litedown does here - that may end up being a better default.

**Comment by Abhi-1U** [comment]
I think it is possible to write a pandoc lua filter for this, by increasing the header level and modifying numbering. A similar filter exists in [rjtools](https://github.com/rjournal/rjtools/blob/main/inst/sec-depth.lua) package.

**Comment by Abhi-1U** [comment]
Reopening this issue for the reasons:

1. It doesn't follow [best practices for accessibility](https://www.a11yproject.com/posts/how-to-accessible-heading-structure/?utm_source=labnotes.org#best-practices-summarized), as already mentioned.
2. It doesn't follow general practice for authoring R Markdown documents. E.g. the Rmd and Qmd templates in RStudio use `<h2>` for the equivalent of \section (top-level section header).

**Comment by hturner** [comment]
Adding proposed solution:

* Use <h2> as the top-level header (map \section -> <h2>, \subsection -> <h3>, \subsubsection -> <h4>)
* Modify the "auto-number-sec" javascript to add numbers in the LaTeX style for these headers (might be as simple as substituting h3 for h2 and h2 for h1 in current code).
