### ISSUE TITLE
"Checking for pandoc version" text redundant?

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#85]
Several of the helpfiles begin with

```
#' # Checking for pandoc version
#' # texor works with pandoc version >= 2.17
```

([example](https://github.com/Abhi-1U/texor/blob/d608a289f9a49363c8ebab65587d59609e5d14ff/R/automation-tools.R#L20-L21)). But no checking seems to be done - at least the example code that follows doesn't explicitly check the pandoc version, so this comment is confusing.

Can the comment be deleted? Is the check done automatically or should the user do this? Maybe it is better as a message on package load?

**Comment by Abhi-1U** [comment]
The comment was indeed an oversight, the code following this comment had a simple version check for pandoc, which was superseded by internal pandoc checks. (77d9cd0aa53bb3bfe114af1964cdf2c698da4e18) fixes the comments in the examples.
The check messages would only be shown if the version is older version of pandoc is installed and to avoid conversion failures in that case. (8b4c691b01aa038e2f896dd36c15a1684b5f145f) will update the existing check messages and make sure it is consistent throughout the package.
