### ISSUE TITLE
Correct vignette builder for bookdown vignette

### ISSUE THREAD

**Issue by hturner** [Abhi-1U/texor#94]
Currently `rnw_to_rmd()` uses the wrong vignette builder in the YAML header for bookdown vignettes. The vignette builder must be `knitr::rmarkdown` for citations, section numbering and other features to work correctly.

Example of including converted Rmd in a package:

```
## create a package
usethis::create_package()

## copy to files to working directory
article_dir <- "rnw_to_rmd"
dir.create(article_dir)
file.copy(system.file(file.path("doc", "parallel.Rnw"), package = "parallel"),
          file.path(article_dir ,  "parallel.Rnw"))
download.file("https://svn.r-project.org/R/trunk/src/library/parallel/vignettes/parallel.bib",
              file.path(article_dir , "parallel.bib"))

## N.B. must be full path not relative path to work
texor::rnw_to_rmd(normalizePath(file.path(article_dir,  "parallel.Rnw")),
  front_matter_type = "vignettes",
  clean_up = TRUE,
  autonumber_eq = TRUE,
  autonumber_sec = TRUE)

## render 
rmarkdown::render(file.path(article_dir, "parallel.Rmd"))
browseURL(normalizePath(file.path(article_dir, "parallel.html")))

## Copy Rmd as vignette for new package
usethis::use_build_ignore("rnw_to_rmd")
usethis::use_vignette("parallel")

file_list <- setdiff(list.files(article_dir), "parallel.Rnw")
file_list <- normalizePath(file.path(article_dir, file_list))

file.copy(file_list, "vignettes", 
          overwrite = TRUE, recursive = TRUE)
          
## !! Need to edit .Rmd
## from  %\VignetteEngine{knitr::knitr}
## to   %\VignetteEngine{knitr::rmarkdown}

## Also update DESCRIPTION (bookdown rather than rmarkdown)
## Suggests: 
##    bookdown,
##    knitr
## VignetteBuilder: knitr

usethis::build_vignettes()
```

We may be able to simplify this example with a templating package that does not assume use of `rmarkdown_vignette()`, maybe pkgKitten.

We may want `rnw_to_rmd()` to return a message about adding bookdown and knitr to `Suggests` and adding `knitr` as the `VignetteBuilder` in the DESCRIPTION - a package that previously used a Sweave vignette would not have these entries. Or maybe we even want a helper function or to extend `rnw_to_rmd` to fix the DESCRIPTION too, assuming that for an existing package, `rnw_to_rmd` is run from the root of the package.

**Comment by Abhi-1U** [comment]
Completed with commit (6cd74512492a17bd16845535173d1f2e1183dca6) and (378a3825c1be3c3b059479c4a31e9ad6e7b1fb5f).
